CREATE TABLE `data_platform_jp_bis_item_data`
(
    `ItemBuyersIdentifier`                                              varchar(100) NOT NULL,                      
    `ItemSellersIdentifier`                                             varchar(100) NOT NULL,                     
	`InvoiceLineIdentifer`			                                    varchar(16) DEFAULT NULL,
	`InvoiceLineNote`			                                        varchar(200) DEFAULT NULL,
	`InvoicedQuantity`			                                        float(15) DEFAULT NULL,
	`InvoiceLineNetAmount`			                                    float(13)DEFAULT NULL,
	`InvoiceLineBuyerAccountingReference`			                    varchar(200) DEFAULT NULL,
	`InvoicePeriodStartDate`			                                date DEFAULT NULL,
	`InvoicePeriodEndDate`			                                    date DEFAULT NULL,
	`DespatchAdviceLine`                                                varchar(16) DEFAULT NULL,
	`DespatchAdviceReference`			                                varchar(16) DEFAULT NULL,
	`ReferencedPurchaseOrderLineReference`			                    varchar(16) DEFAULT NULL,
	`PurchaseOrderReference`                                            varchar(16) DEFAULT NULL,
	`InvoiceLineDocumentIdentifer`			                            varchar(16) DEFAULT NULL,
	`DocumentTypeCode`			                                        varchar(4) DEFAULT NULL,
	`InvoiceLineObjectIdentifier`			                            varchar(16) DEFAULT NULL,
	`Selector`			                                                varchar(16) DEFAULT NULL,
	`SyntaxQualifier`			                                        varchar(4) DEFAULT NULL,
	`InvoiceLineAllowanceReasonCode`                       			    varchar(200) DEFAULT NULL,
	`InvoiceLinelAllowanceReason`                                       varchar(16) DEFAULT NULL,
	`InvoiceLineAllowancePercentage`			                        float(13)DEFAULT NULL,
	`InvoiceLineAllowanceAmount`		     	                        float(13)DEFAULT NULL,
	`InvoiceLineAllowanceBaseAmount`                                    float(13)DEFAULT NULL,
	`TaxScheme`			                                                varchar(16) DEFAULT NULL,
	`SyntaxQualifier`			                                        varchar(4) DEFAULT NULL,
	`InvoiceLineChargeReasonCode`			                            varchar(200) DEFAULT NULL,
	`InvoiceLineChargeReason`	                                        varchar(16) DEFAULT NULL,
	`InvoiceLineChargePercentage`			                            float(13)DEFAULT NULL,
	`InvoiceLinelChargeAmount`			                                float(13)DEFAULT NULL,
	`InvoiceLineChargeBaseAmount`                                       float(13)DEFAULT NULL,
	`ItemDescription`			                                        varchar(200) DEFAULT NULL,
	`ItemName`			                                                varchar(200) DEFAULT NULL,
	`ItemStandardIdentifier`			                                varchar(16) DEFAULT NULL,
	`ItemCountryOfOrigin`			                                    varchar(4) DEFAULT NULL,
	`DocumentTypeCode`			                                        varchar(4) DEFAULT NULL,
	`InvoicedItemTaxCategoryCode`			                            varchar(4) DEFAULT NULL,
	`InvoicedItemTaxRate`			                                    float(6) DEFAULT NULL,
	`UnitTax`			                                                float(13)DEFAULT NULL,
	`ClassifiedTaxScheme`		                                        varchar(16) DEFAULT NULL,
	`ItemAttributeName`                                                 varchar(200) DEFAULT NULL,
	`ItemAttributeValue`                                                varchar(200) DEFAULT NULL,
	`ItemClassificationIdentifier`			                            varchar(200) DEFAULT NULL,
	`ItemNetPrice`			                                            float(13) DEFAULT NULL,
	`ItemPriceBaseQuantity`			                                    float(15) DEFAULT NULL,
	`Syntax qualifier`                                                  float(15) DEFAULT NULL,
	`ItemPriceDiscount`			                                        float(13) DEFAULT NULL,
	`ItemGroossPrice`       			                                float(13) DEFAULT NULL,                                                     

  PRIMARY KEY (`ItemBuyersIdentifier`, `ItemSellersIdentifier`),
  
  ) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;